name: 'ccache-download-upload-redis'
description: 'An GitHub Action for using ccache-upload-redis / ccache-download-redis
to uploads / downloads the contents of the local ccache cache from a Redis remote storage.'
author: 'berlin4apk'
branding:
  icon: lock
  color: orange
inputs:
  REDIS_CONF:
    description: 'DNS or IP of redis server'
    required: false
    default: 'localhost:6379'
  REDIS_USERNAME:
    description: 'redis username'
    required: false
  REDIS_PASSWORD:
    description: 'redis password'
    required: false
  CCACHE_DIR:
    description: 'CCACHE_DIR Path to the CCACHE_DIR'
    required: false
    default: '~/.cache/ccache'
  DO_UPLOAD:
    description: 'run ccache-upload-redis'
    required: false
    default: 'false'
  DO_DOWNLOAD:
    description: 'run ccache-download-redis'
    required: 'false'
runs:
  using: "composite"
  steps:
    - name: Run ccache-upload-redis
      if: (inputs.DO_UPLOAD != null)
      run: |
        ccache-upload-redis
      shell: bash
      env: |
        REDIS_CONF=${{ inputs.REDIS_CONF }}
        REDIS_USERNAME=${{ inputs.REDIS_USERNAME }}
        REDIS_PASSWORD=${{ inputs.REDIS_PASSWORD }}
        CCACHE_DIR=${{ inputs.CCACHE_DIR }}

    - name: Run ccache-download-redis
      if: (inputs.DO_DOWNLOAD != null)
      run: |
        ccache-download-redis
      shell: bash
      env: |
        REDIS_CONF=${{ inputs.REDIS_CONF }}
        REDIS_USERNAME=${{ inputs.REDIS_USERNAME }}
        REDIS_PASSWORD=${{ inputs.REDIS_PASSWORD }}
        CCACHE_DIR=${{ inputs.CCACHE_DIR }}

